require: rubocop-rspec

AllCops:
  DisplayCopNames: yes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Style/EmptyElse:
  EnforcedStyle: empty

Style/Documentation:
  Enabled: no

Metrics/LineLength:
  Max: 120
