require: rubocop-rspec

AllCops:
  DisplayCopNames: yes
  NewCops: enable
  SuggestExtensions: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Layout/LineLength:
  Max: 120

Style/EmptyElse:
  EnforcedStyle: empty

Style/Documentation:
  Enabled: no

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: no

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MessageSpies:
  Enabled: false

RSpec/IndexedLet:
  Max: 2
