require: rubocop-rspec

AllCops:
  DisplayCopNames: yes
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Layout/LineLength:
  Max: 120

Style/EmptyElse:
  EnforcedStyle: empty

Style/Documentation:
  Enabled: no
