require: rubocop-rspec

AllCops:
  DisplayCopNames: yes

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/IndentHash:
  EnforcedStyle: consistent

Style/IndentArray:
  EnforcedStyle: consistent

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Style/EmptyElse:
  EnforcedStyle: empty

Style/Documentation:
  Enabled: no

Metrics/LineLength:
  Max: 120
